### PR TITLE
Backend setup

### LINKED ISSUE #50: [Backend] Initial Server Setup
I would like to start working on the backend.
-Add dependencies
-Connect Database
-Add required models
-Set up routes as needed

### PR DESCRIPTION
**Pull request by Kriti-bit**
I'm still working on this issue, I'll let you know once completed.

## Issue solved

Closes: #50 
<br/><br/>

#### Added db config, created folders, added dependencies

<br/>

## Types of changes made:

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update (Documentation content changed)
-   [ ] Other (please describe):

<br/>

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Comment by Kriti-bit** [comment]
@yash982000 please review the changes
thanks

**Review by yash982000 — APPROVED** [review]
Looks good :)

**Comment by Kriti-bit** [comment]
Thank you @yash982000, please add required GSSoC labels

**Comment by yash982000** [comment]
> Thank you @yash982000, please add required GSSoC labels

@Kriti-bit Done!!

**Pull request merged**
