### PR TITLE
Added Hover Effect.

### LINKED ISSUE #70: Hover Effect to Buttons
I would like to design the navbar by changing font and wants to provide a hovering effect to the components like Home, About-Us, Contact-Us, Services.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by vanshika2906**
Fixed #70

## Issue solved

Closes: #70
<br/><br/>

#### Brief description of what is fixed/changed
Added hover effect to the links in navbar.

<br/>

## Types of changes made:

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update (Documentation content changed)
-   [ ] Other (please describe):

<br/>

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

<br/>

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
image

<br/>

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by yash982000 — CHANGES_REQUESTED** [review]
@vanshika2906 Can you please check about the merge conflicts?

**Comment by vanshika2906** [comment]
Hi @yash982000 please found screenshot for your reference. Let me know in case of any changes. Thankyou!
image

**Comment by yash982000** [comment]
> Hi @yash982000 please found screenshot for your reference. Let me know in case of any changes. Thankyou!
> image

@vanshika2906 I am confused about how the alignment work here and how hover is working here. It would be better if you can add a GIF or small video link from drive.

**Review by yash982000 — CHANGES_REQUESTED** [review]
@vanshika2906 I am confused about how the alignment work here and how hover is working here. It would be better if you can add a GIF or small video link from drive.

**Comment by vanshika2906** [comment]
Hello @yash982000 . Go through the link for better understanding. Thankyou!
 [Link](https://drive.google.com/file/d/1CzqC0ROzd7a2fmiiBSLLrPn0ZA8QVYS8/view?usp=sharing)

**Comment by yash982000** [comment]
> Hello @yash982000 . Go through the link for better understanding. Thankyou!
> [Link](https://drive.google.com/file/d/1CzqC0ROzd7a2fmiiBSLLrPn0ZA8QVYS8/view?usp=sharing)

Looks good :)

**Review by yash982000 — APPROVED** [review]
Looks good :)

**Comment by vanshika2906** [comment]
Hello @yash982000 , I think after merging I didn't get any scores on leaderboard may be because of no label assigned. So, is it now possible that you will assign label and that will get reflected to my leaderboard? Please guide me if I I can do anything from side. Thankyou!

**Pull request merged**
