### PR TITLE
navbar

### PR DESCRIPTION
**Pull request by kumarishalini6**
Error:- The navbar was not working properly

I have remake the navbar now its working perfectly and also it is responsive and added SERVICE page in component it was mention in navbar only.
React App - Personal - Microsoft​ Edge 4_14_2021 09_08_13 AM
React App - Personal - Microsoft​ Edge 4_14_2021 09_09_05 AM

### CODE REVIEW

**Review by yash982000 — CHANGES_REQUESTED** [review]
Can you once confirm if this is not done by anyone else?
Because I guess someone was doing About Us and Contact Page.
Please go through all the issues and all the designs to once verify so that there is no double work for the same thing and same coding.

**Comment by kumarishalini6** [comment]
This is navbar issue no one was working on it.
I have checked someone is creating issue about the "about alumni" and my issue is about "about project" i guess these are different things. And while i was creating issue you also allow 2 people to work on it but you assign issue only me.

**Comment by yash982000** [comment]
@kumarishalini6 There are some conflicts in this PR. Can you check and resolve this?
If not possible, you can close this and open a new one.

**Comment by kumarishalini6** [comment]
conflicts solved

**Comment by kumarishalini6** [comment]
please review this issue also

**Review by yash982000 — COMMENTED** [review]
Done..!!

**Pull request merged**
