### PR TITLE
Share Something Page Design

### PR DESCRIPTION
**Pull request by SAHU-01**
This pr has the design for share something page of the website i.e. Issue No #23 

that page looks like this:

share anything

### CODE REVIEW

**Comment by yash982000** [comment]
> This pr has the design for share something page of the website i.e. Issue No #23
> 
> that page looks like this:
> 
> share anything

This is an image only right?
We do have the designs for share opportunities already in the folder. Do check it out.

**Review by yash982000 — CHANGES_REQUESTED** [review]
This is an image only right?
We do have the designs for share opportunities already in the folder. Do check it out.

**Comment by SAHU-01** [comment]
It's not for share oppurtunities page, please go through issue no #23 ,the instagram feed idea page,to share anything,I was assigned to give a design for that page!! and after discussing with you and chetna ,this was the final design that was chosen ,thus I made a pr!!

**Review by yash982000 — CHANGES_REQUESTED** [review]
Have you shown the final design to @ChetnaNSharma?
If not, can you please confirm with @ChetnaNSharma once?
I will do according to the requirements and merge it if she agrees.

**Comment by SAHU-01** [comment]
> Have you shown the final design to @ChetnaNSharma?
> If not, can you please confirm with @ChetnaNSharma once?
> I will do according to the requirements and merge it if she agrees.

Yes I've shown her,and she has approved it

**Pull request merged**
