### PR TITLE
Ourreach

### LINKED ISSUE #98: Our reach
I want to add our reach page as shown in the image below.

@yash982000 @ChetnaNSharma 
please assign this to me.

### PR DESCRIPTION
**Pull request by ChitvanRamani22**
## Issue solved

Closes: #98
<br/><br/>

## Changes Proposed

I have added our reach section with animated counter.

<br/>

## Checklist:

-   [ y] My code follows the style guidelines of this project
-   [ y] I have performed a self-review of my own code
-   [ ]y I have commented my code, particularly in hard-to-understand areas
-   [ y] I have made corresponding changes to the documentation
-   [ y] My changes generate no new warnings
-   [ y] My changes does not break the current system and it passes all the current test cases.

<br/>

## Screenshots

https://user-images.githubusercontent.com/68965499/118591240-7980fe00-b7c1-11eb-8280-6fe720411098.mp4

<br/>

@yash982000 please review this pr.

### CODE REVIEW

**Review by yash982000 — COMMENTED** [review]
Looks good but have you referenced it to the right issue?

**Comment by ChitvanRamani22** [comment]
@yash982000 sorry for that.
I have corrected it.

**Comment by ChitvanRamani22** [comment]
@yash982000 please assign labels to the pr.

**Comment by ChitvanRamani22** [comment]
@yash982000 thanks!

**Pull request merged**
