### PR TITLE
Enhancing README.md

### PR DESCRIPTION
**Pull request by Kriti-bit**
Hi, I am a GSSoC'21 Participant.
I have tried to enhance the README.md file. Please review the changes and let me know if you want me to change anything.
Thanks!

### CODE REVIEW

**Comment by yash982000** [comment]
> Hi, I am a GSSoC'21 Participant.
> I have tried to enhance the README.md file. Please review the changes and let me know if you want me to change anything.
> Thanks!

Heyy @Kriti-bit Thanks for trying to contribute. But can you explain in detail what changes you have done apart from formatting. I am unable to see them. Please elaborate and I will be happy to assign and merge it for you. Thanks.

**Review by yash982000 — COMMENTED** [review]
Heyy @Kriti-bit Thanks for trying to contribute. But can you explain in detail what changes you have done apart from formatting. I am unable to see them. Please elaborate and I will be happy to assign and merge it for you. Thanks.

**Comment by Kriti-bit** [comment]
Hi @yash982000, in this I've focused more on enhancing the visual effect of README.md by adding pictures and enhancing the overall look of the README.md file.
I'm open to suggestions about what else I should add
Thanks

**Comment by yash982000** [comment]
> Hi @yash982000, in this I've focused more on enhancing the visual effect of README.md by adding pictures and enhancing the overall look of the README.md file.
> I'm open to suggestions about what else I should add
> Thanks

This task was opened by someone earlier. And due to it, there is a merge conflict. If you still want to work on it, open a new issue and give proper screenshots about the preview of the readme. Since, we have had enough thing in the readme at the moment, we can only add if it really seems nice and useful for this project repository. Thanks :)

**Comment by Kriti-bit** [comment]
okay, noted
Thanks

**Pull request closed without merging**
