### PR TITLE
Designed Login Register Page

### PR DESCRIPTION
**Pull request by avinashjha1320**
@ChetnaNSharma @yash982000 I have also added switch side animation for changing the registration form to the login form. #21 
image
image

### CODE REVIEW

**Comment by yash0501** [comment]
There is one suggestion that you just change the color of fontawesome labels to some lighter color i.e. white or similar in the create an account panel. You can take help  of this section.
Screenshot (335)
For more details about this topic, refer this webpage: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

**Comment by yash982000** [comment]
@avinashjha1320 Can you also please upload the GIF to show the animation?

**Comment by yash982000** [comment]
> @avinashjha1320 Can you also please upload the GIF to show the animation?

@avinashjha1320

**Comment by avinashjha1320** [comment]
@yash982000 I show the design to the project admin..but then she asked me to change it..and now I am working on it...i will contact you after completing the design.

**Comment by yash982000** [comment]
> @yash982000 I show the design to the project admin..but then she asked me to change it..and now I am working on it...i will contact you after completing the design.

@avinashjha1320 Oh okay, no worries. I wasn't aware of that. So, you can contact her only and I will take follow-up or merge it when she agrees.

**Pull request closed without merging**
