### PR TITLE
About Us and Contact Us page

### PR DESCRIPTION
**Pull request by kumarishalini6**
I have added About Us Page .

About Us

React App - Personal - Microsoft​ Edge 4_15_2021 09_36_32 AM

Contact Us
React App - Personal - Microsoft​ Edge 4_15_2021 09_36_12 AM

### CODE REVIEW

**Review by yash982000 — CHANGES_REQUESTED** [review]
Can you once confirm if this is not done by anyone else?
Because I guess someone was doing About Us and Contact Page.
Please go through all the issues and all the designs to once verify so that there is no double work for the same thing and same coding.

**Comment by kumarishalini6** [comment]
Ok I'll check and inform you

**Comment by yash982000** [comment]
> Ok I'll check and inform you

Great :)

**Comment by kumarishalini6** [comment]
Should I check closed issue

**Comment by kumarishalini6** [comment]
I have checked someone is creating issue about the "about alumni" and my issue is about "about project" i guess these are different things. And while i was creating issue you also allow 2 people to work on it but you assign issue only me.

**Review by yash982000 — APPROVED** [review]
Looks good...!!

**Comment by yash982000** [comment]
@kumarishalini6 There are some conflicts in this PR. Can you check and resolve this?
If not possible, you can close this and open a new one.

**Comment by kumarishalini6** [comment]
Thanks
No worries I have solved that conflicts

**Comment by yash982000** [comment]
> Thanks
> No worries I have solved that conflicts

Great. Merged :)

**Pull request merged**
