### PR TITLE
Isssue #10 Contributing to README.md

### PR DESCRIPTION
**Pull request by Aniketbhanderi**
Changes made:
- Linking contributor.md file to README.md
- GSSOC amd its mentor information added.(@yash982000  Please tell other 2 mentors usernames so I can add them).
- Visual Chnages of paragraphs and added badges for better asthetics.

### CODE REVIEW

**Comment by Aniketbhanderi** [comment]
@yash982000  please review commit and merge them,  and any other tips or additional improvements for me are most welcome. I would try my best to do it.

**Review by yash982000 — COMMENTED** [review]
Try to detail and elaborate it still more. Merged for now.

**Review by yash982000 — COMMENTED** [review]
Also, add photos of mentors, project admin, and contributors in a step-wise manner as in general open-source projects which are funded. You can easily find those templates. Let me know if you need some help.

**Comment by yash982000** [comment]
> Also, add photos of mentors, project admin, and contributors in a step-wise manner as in general open-source projects which are funded. You can easily find those templates. Let me know if you need some help.

@Aniketbhanderi  Also, have a white background for GSSoC text. It is not properly visible.

**Comment by Aniketbhanderi** [comment]
Okay @yash982000 
I will try to implement all the suggestion. Thanks for elaborating !

**Comment by yash982000** [comment]
[](url)

> Okay @yash982000
> I will try to implement all the suggestion. Thanks for elaborating !

Most welcome. All the best :)

**Comment by yash982000** [comment]
> Okay @yash982000
> I will try to implement all the suggestion. Thanks for elaborating !

@Aniketbhanderi Any updates for this?

**Comment by Aniketbhanderi** [comment]
@yash982000  GSSOC text image pr created.
I am not able to find other mentors github account, have seen them in discord I guess. So please ping their usernames so I can add photos and also detais of project admins.

**Comment by yash982000** [comment]
> @yash982000 GSSOC text image pr created.
> I am not able to find other mentors github account, have seen them in discord I guess. So please ping their usernames so I can add photos and also detais of project admins.

mksharma1 , yash garg i don't know, can mail him and ask but he is not active

**Pull request merged**
