### PR TITLE
Issue Template Added

### LINKED ISSUE #52: Create a template for issues
I would like to create a template for the issues raised.

### PR DESCRIPTION
**Pull request by Kriti-bit**
## Issue solved
Closes: #52 

#### Brief description of what is fixed/changed
I have added 2 template for issues
1) Bug Reports
2) Request for new features

When a user clicks on `New Issue` , two options will be displayed namely, `Feature Request` and `Bug Report`. After selecting one of the options templates as in the screenshot will be set up.

## Types of changes made:

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update (Documentation content changed)
-   [ ] Other (please describe):

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

image

image

### CODE REVIEW

**Comment by Kriti-bit** [comment]
@yash982000 please let me know in case any changes are required.

**Review by yash982000 — CHANGES_REQUESTED** [review]
@Kriti-bit Can you add some screenshots of what the final output looks like?
It would help me easily and fast understand the changes. :)

**Comment by Kriti-bit** [comment]
@yash982000 It'll look similar to this after clicking on `new issue`. Depending on the type of issue the template will open accordingly.
image

**Comment by yash982000** [comment]
> @yash982000 It'll look similar to this after clicking on `new issue`. Depending on the type of issue the template will open accordingly.
> image

Okay, you may proceed!

**Review by yash982000 — APPROVED** [review]
Looks good!!

**Pull request merged**
