### PR TITLE
Save tokens

### LINKED ISSUE #109: saving tokens (backend)
**Is your feature request related to a problem? Please describe.**

currently, after signing up the token which gets provided to the student user does not get saved to the tokens array of the student entry in the collection

**Describe the solution you'd like**

adding some code to the sign-in route to save the token to 'tokens' array

@yash982000, @ChetnaNSharma can you please assign this issue to me

### PR DESCRIPTION
**Pull request by mitalirs**
## Issue solved

Closes: #109
<br/><br/>

####  added save tokens code and fixed some errors

<br/>

## Types of changes made:

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update (Documentation content changed)
-   [ ] Other (please describe):

<br/>

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

<br/>

### CODE REVIEW

**Comment by mitalirs** [comment]
@ChetnaNSharma, @yash982000 please review the pull request

**Review by yash982000 — APPROVED** [review]
Cool

**Comment by mitalirs** [comment]
@yash982000, can you please add the appropriate labels?

**Comment by yash982000** [comment]
> @yash982000, can you please add the appropriate labels?

Done :)

**Pull request merged**
