### PR TITLE
Contribution.md changes made.

### PR DESCRIPTION
**Pull request by pragati-kumar**
Added label categories of the issues and what they signify. Made the documentation more to the point and fixed the committing process typo.

### CODE REVIEW

**Review by yash982000 — APPROVED** [review]
Can you add some screenshots to the significant changes?? Since I am not able to gather what good things are added. Also, this has merge conflicts so you might want to open a new issue or solve the conflict if you can.

**Comment by pragati-kumar** [comment]
> Can you add some screenshots to the significant changes?? Since I am not able to gather what good things are added. Also, this has merge conflicts so you might want to open a new issue or solve the conflict if you can.

Sure. Just a minute

**Comment by pragati-kumar** [comment]
Screenshot 2021-03-30 at 11 57 44 PM
Screenshot 2021-03-30 at 11 58 24 PM
Screenshot 2021-03-30 at 11 59 08 PM

**Review by yash982000 — APPROVED** [review]
Steps are cleared more precisely for contributing.

**Pull request merged**
