### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aniketbhanderi**
Logo Updated for Dark Mode.

### CODE REVIEW

**Review by yash982000 — CHANGES_REQUESTED** [review]
Can you add the screenshot?

**Review by yash982000 — CHANGES_REQUESTED** [review]
Actually, suppose I am in dark mode and some other members are in light mode?
How does it simultaneously work for both?
I can only understand if a screenshot is attached :)

**Comment by Aniketbhanderi** [comment]
> Can you add the screenshot?
Yes sure
image
image

**Review by yash982000 — APPROVED** [review]
Great, looks awesome now.

**Pull request merged**
