### PR TITLE
Solves issue #40 Animation and Button addition in testimonial part

### LINKED ISSUE #40: Improvement in the testimonials section
The testimonial page can be improved by adding animation and also adding a hover effect on them.
please @mksharma1 @Aniketbhanderi @yash982000 @M2kishore @pragati-kumar  assign this issue to me.

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
Fixes #40 
The flip card animation has been added which on being hovered upon displays the reviews which the people has and also a dropdown button for the requests has been created which on being hovered displays the request and a link to the linkedin profile.

Before-
image
 After-
image
GIF-
Testimonial-4
It is based on the issue #40.
@yash982000 kindly look into it.

### CODE REVIEW

**Review by yash982000 — CHANGES_REQUESTED** [review]
@Khushi-agarwal Looks good, I have a couple of doubts.

Where is the sub-option drop menu of requests leading to when one selects them?

Also, I am unable to see LinkedIn or resume link for now.

And, this is perfect for requests thing. But you have to make it separate from the testimonials page. Like requests will have names and resume or linkedin link under it's section.

I am not able to interpret from this GIF if it is working like that or not because I can only see 1testimonials and review cards.

**Comment by Khushi-agarwal** [comment]
@yash982000  In the requests section,I have not added the sub option drop menu as on hovering over requests section it displays the request and the icon of linkedin which will have the link to their profile.
And as you said the separate thing of testimonial and requests, so I have added a drop down list for it instead of having a complete separate thing for it.
I will now add the sub drop option menu which can have separate link for resume or Linkedin.

**Comment by yash982000** [comment]
> @yash982000 In the requests section,I have not added the sub option drop menu as on hovering over requests section it displays the request and the icon of linkedin which will have the link to their profile.
> And as you said the separate thing of testimonial and requests, so I have added a drop down list for it instead of having a complete separate thing for it.
> I will now add the sub drop option menu which can have separate link for resume or Linkedin.

@Khushi-agarwal Yes, please do that and let me know whenever you are done

**Comment by Khushi-agarwal** [comment]
@yash982000 I have added the sub drop menu option for the requests part.
The before gif is the same as above.
After-
after

**Comment by Khushi-agarwal** [comment]
@yash982000 Kindly look into it.

**Comment by yash982000** [comment]
> @yash982000 Kindly look into it.

This looks somewhat good.
Are those reviews still on the same page?

**Comment by yash982000** [comment]
> @yash982000 Kindly look into it.

Also, the thing is that these would not be static number of requests.
There will be requests coming from the backend as per the other user's wish.
So, will the drop-down menu automatically accommodate those new requests along with the links?

**Comment by yash982000** [comment]
@Khushi-agarwal Actually, we will have to drop this idea.
Can you open a new issue or so?
Make this completely different from the testimonials page with a new HTML and CSS file.
The thing you wanted to do in testimonials, we will discuss it here in this thread itself but let's complete first this in a new issue.

We only have a responsive table requirement for the requests section which will contain a name, email, Linkedin, and resume link of the requester. And, final the submit button along with a small description for the reviewer to write and submit it back.

Here is some reference for you:-

https://codepen.io/DrewRyan/pen/YZxYER

https://colorlib.com/wp/css3-table-templates/

https://codepen.io/AllThingsSmitty/pen/MyqmdM

Let me know if you can do it or have any doubts.

**Comment by Khushi-agarwal** [comment]
> > @yash982000 Kindly look into it.
> 
> This looks somewhat good.
> Are those reviews still on the same page?

Yes they are on the same page.

**Comment by Khushi-agarwal** [comment]
> > @yash982000 Kindly look into it.
> 
> Also, the thing is that these would not be static number of requests.
> There will be requests coming from the backend as per the other user's wish.
> So, will the drop-down menu automatically accommodate those new requests along with the links?

Yes,it will increase depending on the number of requests.

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal Actually, we will have to drop this idea.
> Can you open a new issue or so?
> Make this completely different from the testimonials page with a new HTML and CSS file.
> The thing you wanted to do in testimonials, we will discuss it here in this thread itself but let's complete first this in a new issue.
> 
> We only have a responsive table requirement for the requests section which will contain a name, email, Linkedin, and resume link of the requester. And, final the submit button along with a small description for the reviewer to write and submit it back.
> 
> Here is some reference for you:-
> 
> https://codepen.io/DrewRyan/pen/YZxYER
> 
> https://colorlib.com/wp/css3-table-templates/
> 
> https://codepen.io/AllThingsSmitty/pen/MyqmdM
> 
> Let me know if you can do it or have any doubts.

I would love to work on this issue but it's my request that if you could merge this pr which was based on the testimonial page as you liked the idea, so if it could be merged then I would be highly grateful.If you merge only the testimonial part then it would be great for me as it would help me in my gssoc score . @yash982000 I hope you understand.
And regarding the working towards the requests section, it would be my pleasure to work towards it.

**Comment by yash982000** [comment]
@Khushi-agarwal I understand. But the current feature doesn't suffice our requirements.

At the end, this is going to be a full working application so we cannot add things which we don't require now.

With matter to the score, do this table part. And I will count your work by giving a point level more in this PR.

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal I understand. But the current feature doesn't suffice our requirements.
> 
> At the end, this is going to be a full working application so we cannot add things which we don't require now.
> 
> With matter to the score, do this table part. And I will count your work by giving a point level more in this PR.

I believe your words and have created a issue for it. @yash982000

**Comment by yash982000** [comment]
> > @Khushi-agarwal I understand. But the current feature doesn't suffice our requirements.
> > At the end, this is going to be a full working application so we cannot add things which we don't require now.
> > With matter to the score, do this table part. And I will count your work by giving a point level more in this PR.
> 
> I believe your words and have created a issue for it. @yash982000

@Khushi-agarwal I have assigned you and labeled it with points as well which is not the case generally before merging. :)

**Comment by Khushi-agarwal** [comment]
> > > @Khushi-agarwal I understand. But the current feature doesn't suffice our requirements.
> > > At the end, this is going to be a full working application so we cannot add things which we don't require now.
> > > With matter to the score, do this table part. And I will count your work by giving a point level more in this PR.
> > 
> > 
> > I believe your words and have created a issue for it. @yash982000
> 
> @Khushi-agarwal I have assigned you and labeled it with points as well which is not the case generally before merging. :)

Thank you.

**Comment by Khushi-agarwal** [comment]
Fixes #46 
@yash982000 sir,I have created a new html and css page and have added the table as told by you.
Kindly have a look.
The page looks like this-
Requests
All the links of linkedIn and resume are active.

**Comment by yash982000** [comment]
> Fixes #46
> @yash982000 sir,I have created a new html and css page and have added the table as told by you.
> Kindly have a look.
> The page looks like this-
> Requests
> All the links of linkedIn and resume are active.

Perfect!!
I hope it is dynamic and new can be added from the backend.

**Review by yash982000 — APPROVED** [review]
Seems great.

**Comment by yash982000** [comment]
@Khushi-agarwal Merged.!!

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal Merged.!!

Thank you:)

**Pull request merged**
