### PR TITLE
Create chatbot

### LINKED ISSUE #88: Create ChatBot feature
**Is your feature request related to a problem? Please describe.**
Adding  a chatbot feature in the web app.
A button  showing click to chat at the bottom on the home page.

### PR DESCRIPTION
**Pull request by vanshika2906**
## Issue solved

Closes: #88
<br/><br/>

#### Brief description of what is fixed/changed
Added a chatbot feature in the web app.
<br/>

## Types of changes made:

-   [] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update (Documentation content changed)
-   [ ] Other (please describe):

<br/>

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

<br/>

## Screenshots
Please go through the link for better understanding.
[Link](https://drive.google.com/file/d/1ZfbgEMktIFJEsNE3VQi5RcTQGYpXwbdn/view?usp=sharing)

<br/>

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by yash982000 — APPROVED** [review]
Awesome Job :) @vanshika2906

**Review by yash982000 — CHANGES_REQUESTED** [review]
@vanshika2906 I would like to request you to have a look on the merge conflicts so that I can merge it after clearing the conflicts.

**Comment by vanshika2906** [comment]
> @vanshika2906 I would like to request you to have a look on the merge conflicts so that I can merge it after clearing the conflicts.

done @yash982000

**Review by yash982000 — APPROVED** [review]
Looks great :)

**Pull request merged**
