### PR TITLE
404 error page added

### PR DESCRIPTION
**Pull request by ShambhaviSharma0110**
I've added a wireframe for the 404 error page

### CODE REVIEW

**Review by yash982000 — APPROVED** [review]
Can you show some preview/screenshot?

**Comment by yash982000** [comment]
> Can you show some preview/screenshot?

@ShambhaviSharma0110

**Comment by ShambhaviSharma0110** [comment]
image
I'm sorry for the delay

**Review by yash982000 — COMMENTED** [review]
What is the agenda for this?
And when and where will this be used?

**Pull request closed without merging**
